reboot if reload fails

diff --git a/builder/data/usr/bin/bettercap-launcher b/builder/data/usr/bin/bettercap-launcher
--- a/builder/data/usr/bin/bettercap-launcher
+++ b/builder/data/usr/bin/bettercap-launcher
@@ -11,7 +11,10 @@ fi
 
 # check if wifi driver is bugged
 if ! check_brcm; then
-  reload_brcm
+  if ! reload_brcm; then
+    echo "Could not reload wifi driver. Reboot"
+    reboot
+  fi
   sleep 10
 fi
 
